# Generated by Django 5.0.7 on 2024-07-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
